# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Fabric Properties
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Mod Properties
mod_version=2.0.0+26.2
maven_group=de.dafuqs
archives_base_name=fluidvoidfading

# Dependencies
# https://maven.caffeinemc.net/#/releases/net/caffeinemc/sodium-fabric/
sodium_version=0.9.1-beta.4+mc26.2
# required when using sodium
fabric_api_version=0.155.0+26.2