# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.8
yarn_mappings=1.21.8+build.1
fabric_loader_version=0.17.2

neoforge_version=21.8.47

# Mod Properties
mod_version=1.5.0+1.21.8
maven_group=de.dafuqs.fluidvoidfading
mod_id=fluidvoidfading
display_name=Fluid Void Fading
mod_description=Renders fluids flowing into the void, seamlessly
enabled_platforms=fabric,neoforge

# Dependencies
fabric_api_version=0.133.4+1.21.8
sodium_version=mc1.21.6-0.6.13
yarn_mappings_patch_neoforge_version=1.21+build.4