# Gradle Properties
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Minecraft
minecraft_version=26.2.0
minecraft_version_range=[26.2.0,)

# https://projects.neoforged.net/neoforged/neogradle
neogradle_version=7.1.38

# https://neoforged.net/
neoforge_version=26.2.0.12-beta
neoforge_version_range=[26.2.0.12-beta,)

## Mod Properties
mod_version=2.2.0+26.2-neoforge
mod_group_id=de.dafuqs
mod_id=fluidvoidfading
archives_base_name=FluidVoidFading
mod_name=FluidVoidFading
mod_license=GPL-3.0
mod_authors=DaFuqs
mod_description=Renders fluids flowing into the void, seamlessly.
issue_tracker_url=https://github.com/DaFuqs/FluidVoidFading/issues
display_url=https://github.com/DaFuqs/FluidVoidFading

# Dependencies
sodium_version=0.9.1-beta.4+mc26.2